welcome_message: |
  REDEFINE PRECISION MANUFACTURING
hero_carousel_imgs:
  - assets/img/lpprecision/shop_1.jpg
  - assets/img/lpprecision/shop_2.jpg
  - assets/img/lpprecision/shop_3.jpg
  - assets/img/lpprecision/product_10.jpg
get_started_title: No jobs is small to us. Precision in every cut.
get_started_first_paragraph: Equipped with YCM CNC machines and Takisawa CNC turning center, we excel in projects of all scales. From prototypes to large-scale production, we've got you covered.
get_started_second_paragraph: We specialize in precision work with medical-grade metals such as stainless steel, aluminum, and copper, as well as a comprehensive range of plastics from acetal to PEEK.
email: lpprecision@sbcglobal.net
