welcome_message: |
  REDEFINE PRECISION MANUFACTURING
hero_carousel_imgs:
  - assets/img/lpprecision/shop_1.jpg
  - assets/img/lpprecision/shop_2.jpg
  - assets/img/lpprecision/shop_3.jpg
  - assets/img/lpprecision/product_10.jpg
